repos:
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v8.44.0
    hooks:
      - id: eslint
        files: \.[jt]sx?$  # *.js, *.jsx, *.ts, *.tsx
        types: [file]
        additional_dependencies:
          - eslint@8.44.0
          - @typescript-eslint/eslint-plugin@5.61.0
          - @typescript-eslint/parser@5.61.0

  - repo: local
    hooks:
      - id: type-check
        name: type-check
        entry: npx tsc --noEmit
        language: system
        pass_filenames: false
        files: \.[jt]sx?$

  - repo: local
    hooks:
      - id: unit-tests
        name: unit-tests
        entry: npm test
        language: system
        pass_filenames: false
        files: \.[jt]sx?$

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.0.0
    hooks:
      - id: prettier
        files: \.[jt]sx?$  # *.js, *.jsx, *.ts, *.tsx