services:
  - type: web
    name: node-api
    env: node
    buildCommand: npm ci && npm run build && npx prisma migrate deploy
    startCommand: node dist/index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
    healthCheckPath: /health
    autoDeploy: true